stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  image: maven:3.6.0-jdk-11-slim
  script: mvn -Dmaven.test.skip=true -f pom.xml clean package
  artifacts:
    paths:
      - target/*jar
  
deploy:
  stage: deploy
  only:
    - master
  tags:
    - shell
  script:
    - docker build -t visual-cep-pattern_java:0.1 .
    - docker kill visual-cep-pattern_java || true
    - docker rm visual-cep-pattern_java || true
    - docker run -p 8082:8082 --restart=always -d --name=visual-cep-pattern_java visual-cep-pattern_java:0.1

    