build:
  image: maven:3.6.0-jdk-11-slim
  script: mvn -Dmaven.test.skip=true -f pom.xml clean package
  artifacts:
    paths:
      - target/*jar
  
test:
  image: openjdk:11-jre-slim
  script: java -jar target/backen-java-0.0.1-SNAPSHOT.jar

    