stages:
  - build
  - deploy

build:
  stage: build
  tags: 
    - docker
  image: maven:3.6.0-jdk-11-slim
  script: mvn -Dmaven.test.skip=true -f pom.xml clean package
  artifacts:
    paths:
      - target/*jar
  
deploy:
  stage: deploy
  tags:
    - shell
  script:
    - docker build -t visualcepjava:0.1 .
    - docker run --rm -d visualcepjava:0.1 -p 8080 --restart=on-failure:10
 # script: java -jar target/backend-java-0.0.1-SNAPSHOT.jar

    