version: '3.7'

services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka_1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.2.116
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  mongo:
    image: mongo
    hostname: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ifs
      MONGO_INITDB_ROOT_PASSWORD: changeME0815

  mongo-express:
    image: mongo-express
    hostname: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ifs
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeME0815
    depends_on:
      - mongo
